package main

import (
	"fmt"
	"google.golang.org/protobuf/compiler/protogen"
)

// Paths for packages used by code generated in this file,
// relative to the import_prefix of the generator.Generator.
const (
	httprpcPackage = protogen.GoImportPath("github.com/luban-cloud/utils/httprpc")
)

// GenerateHttpRPCFile generates a _httprpc.pb.go file containing httprpc service definitions.
func GenerateHttpRPCFile(gen *protogen.Plugin, file *protogen.File) *protogen.GeneratedFile {
	if len(file.Services) == 0 {
		return nil
	}
	filename := file.GeneratedFilenamePrefix + "_httprpc.pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)
	g.P("// Code generated by protoc-gen-go-httprpc. DO NOT EDIT.")
	g.P("// versions:")
	g.P("// - protoc-gen-go-httprpc v", version)
	g.P("// - protoc             ", protocVersion(gen))
	if file.Proto.GetOptions().GetDeprecated() {
		g.P("// ", file.Desc.Path(), " is a deprecated file.")
	} else {
		g.P("// source: ", file.Desc.Path())
	}
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	mg := httprpc{}
	mg.Init(g)
	mg.Generate(file)
	return g
}

// httprpc is an implementation of the Go protocol buffer compiler's
// plugin architecture.  It generates bindings for tars rpc suppormg.
type httprpc struct {
	gen *protogen.GeneratedFile
}

// Name returns the name of this plugin
func (mg *httprpc) Name() string {
	return "httprpc"
}

// Init initializes the plugin.
func (mg *httprpc) Init(gen *protogen.GeneratedFile) {
	mg.gen = gen
}

// GenerateImports generates the import declaration for this file.
func (mg *httprpc) GenerateImports(file *protogen.File) {
	mg.gen.QualifiedGoIdent(httprpcPackage.Ident("Encoder"))
	mg.gen.QualifiedGoIdent(contextPackage.Ident("Context"))
	mg.gen.QualifiedGoIdent(fmtPackage.Ident("Errorf"))
	mg.gen.QualifiedGoIdent(jsonPackage.Ident("Marshaller"))
}

// P forwards to g.gen.P.
func (mg *httprpc) P(args ...interface{}) { mg.gen.P(args...) }

// Generate generates code for the services in the given file.
func (mg *httprpc) Generate(file *protogen.File) {
	mg.GenerateImports(file)

	mg.P()

	for i, service := range file.Services {
		mg.generateService(file, service, i)
	}
}

// generateService generates all the code for the named service
func (mg *httprpc) generateService(file *protogen.File, service *protogen.Service, index int) {
	// generate the method
	mg.generateMethod(service)

	mg.generateClientCode(service)
}

func (mg *httprpc) generateClientCode(service *protogen.Service) {
	serviceName := upperFirstLatter(service.GoName)

	mg.P(fmt.Sprintf(`// %sClient implement
		type %sHttpClient struct {
			url string
		}
	`, serviceName, serviceName))

	mg.P(fmt.Sprintf(`func New%sHttpClient(url string) *%sHttpClient {
		return &%sHttpClient{url: url}
	}`, serviceName, serviceName, serviceName))
	mg.P()

	for _, method := range service.Methods {
		mg.generateClientMethod(serviceName, method)
		mg.P()
	}
}

func (mg *httprpc) generateClientMethod(serviceName string, method *protogen.Method) {
	mg.P(fmt.Sprintf(`func (client *%sHttpClient) %s(ctx context.Context, req *%s) (*%s, error) {
			resp := %s{}
			err := httprpc.HttpRPC(ctx, client.url, "%s", req, resp, nil)
			if err != nil {
				return nil, err
			}
			return &resp, nil
		}`, serviceName, method.GoName, method.Input.GoIdent.GoName, method.Output.GoIdent.GoName, method.Output.GoIdent.GoName, method.GoName))
}

//func (mg *httprpc) generateClientMethodOri(serviceName string, method *protogen.Method) {
//	mg.P(fmt.Sprintf(`func (client *%sClient) %sOri(ctx context.Context, req *%s, ipport string) (*%s, error) {
//			input, err := proto.Marshal(req)
//			if err != nil {
//				return nil, err
//			}
//			out, err := client.client.Call(ctx, ipport, "proto", "%s", input)
//			if err != nil {
//				return nil, err
//			}
//			resp := %s{}
//			if err := proto.Unmarshal(out, &resp); err != nil {
//				return nil, err
//			}
//			return &resp, nil
//		}`, serviceName, method.GoName, method.Input.GoIdent.GoName, method.Output.GoIdent.GoName, method.GoName, method.Output.GoIdent.GoName))
//}

//func (mg *httprpc) generateClientBroadcastMethod(serviceName string, method *protogen.Method) {
//	mg.P(fmt.Sprintf(`func (client *%sClient) Broadcast%s(ctx context.Context, req *%s) (*%s, map[string]error) {
//			input, err := proto.Marshal(req)
//			if err != nil {
//				return nil, err
//			}
//			out, errs := client.client.BroadcastCall(ctx, "", "proto", "%s", input)
//			if errs != nil {
//				return nil, errs
//			}
//			resp := %s{}
//			if err := proto.Unmarshal(out, &resp); err != nil {
//				return nil, err
//			}
//			return &resp, nil
//		}`, serviceName, method.GoName, method.Input.GoIdent.GoName, method.Output.GoIdent.GoName, method.GoName, method.Output.GoIdent.GoName))
//}

func (mg *httprpc) generateMethod(service *protogen.Service) {
	serviceName := upperFirstLatter(service.GoName)
	mg.P(fmt.Sprintf(`// %sCall is used to call the implement of the defined method.
	func %sHttpCall(ctx context.Context, impl any, method string, input []byte) (out []byte, err error) {
		obj, ok := impl.(I%sServer)
		if !ok {
			return nil, fmt.Errorf("method %%s not implement", method)
		}
		_ = obj
		switch method {`, serviceName, serviceName, serviceName))
	for _, method := range service.Methods {
		mg.P(fmt.Sprintf(`case "%s":
			var req %s
			if err = json.Unmarshal(input, &req); err != nil {
				return nil, err
			}
			resp, err := obj.%s(ctx, &req)
			if err != nil {
				return nil, err
			}
			out, err = json.Marshal(resp)
			if err != nil {
				return nil, err
			}`, method.GoName, mg.gen.QualifiedGoIdent(method.Input.GoIdent), upperFirstLatter(method.GoName)))
	}
	mg.P("default:")
	mg.P("return nil, fmt.Errorf(\"method %s not implement\", method)")
	mg.P("}")
	mg.P("return out, nil")
	mg.P("}")
	mg.P()
}
